### ISSUE TITLE
部署遇到问题 

### ISSUE THREAD

**Issue by liangsize** [chowa/ejyy#16]
无法部署，在执行npm命令就遇到了版本不符及无法安装，npm WARN ejyy_server@1.0.0 No description
npm WARN ejyy_server@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
等等问题，如何解决

**Comment by SmokingRabbit** [comment]
nodejs版本是多少，用的什么系统？有没有删除node_modules重新安装尝试？

**Comment by liangsize** [comment]
目前遇到了npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ejyy_web@1.0.0 dist: `npm run iconfont && vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ejyy_web@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /www/server/nodejs/v14.16.1/cache/_logs/2024-01-23T14_46_03_143Z-debug.log

**Comment by liangsize** [comment]
NodeJS版本号：1.9
Node版本号：V12.15.0
系统：CentOS 7.9.2009 x86_64(Py3.7.9)
有重新试过

**Comment by liangsize** [comment]
能否加QQ私聊呢
