### ISSUE TITLE
server服务端报错

### ISSUE THREAD

**Issue by fengfeng34qy** [chowa/ejyy#7]
![输入图片说明](https://images.gitee.com/uploads/images/2022/0527/141810_1ee3fb52_5548918.png "在这里输入图片标题")
![输入图片说明](https://images.gitee.com/uploads/images/2022/0527/142139_7ea52801_5548918.png "在这里输入图片标题")
环境：
win10、nodejs@12.1.0

**Comment by SmokingRabbit** [comment]
获取最新版本，重新安装依赖后看看
